Repository kubevirt/kubevirt-velero-plugin, pull requests merged in 2022-03, with the labels that each got.

#25 Make tests more universal
  tests/dv_backup_test.go
  tests/framework/framework.go
  tests/resource_filtering_test.go
  tests/utils.go
  tests/vm_backup_test.go
Labels: lgtm, approved, dco-signoff: yes, size/XL

#26 Release test bin
  hack/release.sh
  pkg/plugin/pod_restore_item_action.go
Labels: lgtm, approved, size/XS, dco-signoff: yes

#27 S3 Region extraced to ENV
  tests/dv_backup_test.go
  tests/framework/framework.go
  tests/utils.go
Labels: lgtm, approved, size/S, dco-signoff: yes

#28 Correct vm test to run on WFFC storage
  tests/vm_backup_test.go
Labels: lgtm, approved, size/S, dco-signoff: yes

#30 Fix typo in release script
  hack/release.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#33 Emit junit report in artifacts dir
  hack/run-ci.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#32 use external KUBECONFIG
  Makefile
  hack/build/run-functional-tests.sh
  hack/cluster-deploy-prerequisites.sh
  hack/cluster-up.sh
  hack/config.sh
  hack/velero/undeploy-velero.sh
Labels: lgtm, approved, dco-signoff: yes, size/L

#34 DV test can now run on WFFC storage
  tests/dv_backup_test.go
  tests/utils.go
Labels: lgtm, approved, size/XS, dco-signoff: yes

#38 STORAGECLASS enironment variable
  tests/dv_backup_test.go
  tests/framework/framework.go
  tests/resource_filtering_test.go
  tests/utils.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#39 Select some tests as a core
  tests/dv_backup_test.go
  tests/resource_filtering_test.go
  tests/vm_backup_test.go
Labels: lgtm, approved, size/S, dco-signoff: yes

#40 Simplify KUBECONFIG for tests
  hack/build/run-functional-tests.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#41 Storage class used in vm tests
  tests/resource_filtering_test.go
  tests/utils.go
  tests/vm_backup_test.go
Labels: size/S, dco-signoff: yes

#42 Update objects in loop
  tests/resource_filtering_test.go
  tests/vm_backup_test.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#44 Improve test stability
  cluster-up/cluster/K8S.md
  cluster-up/cluster/K8S_DEV_GUIDE.md
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-1.19/provider.sh
  cluster-up/cluster/k8s-1.20/provider.sh
  cluster-up/cluster/k8s-1.22-ipv6/provider.sh
  cluster-up/cluster/k8s-1.23/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/multus.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.19-vgpu/provider.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.23-vgpu/README.md
  cluster-up/cluster/kind-1.23-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.23-vgpu/provider.sh
  cluster-up/cluster/kind-1.23-vgpu/vgpu-node/node.sh
  cluster-up/cluster/kind-k8s-1.19/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/local/README.md
  cluster-up/hack/common.sh
  tests/resource_filtering_test.go
  tests/utils.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#46 Make local builds
  Makefile
Labels: lgtm, approved, size/S, dco-signoff: yes

#49 Grab exact path of ginkgo binary
  hack/build/build-functest.sh
Labels: lgtm, approved, size/S, dco-signoff: yes

#48 Use builder from quay
  Makefile
  tests/resource_filtering_test.go
Labels: lgtm, approved, size/XS, dco-signoff: yes

#50 Correct directory name
  Makefile
Labels: lgtm, approved, size/XS, dco-signoff: yes
