Repository kubevirt/kubevirt-velero-plugin, pull requests merged in 2022-10, with the labels that each got.

#85 Only use --userns=keep-id for rootless podman
  Makefile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#86 Correct snapshot location configuration
  hack/velero/deploy-velero.sh
  tests/dv_backup_test.go
  tests/utils.go
  tests/vm_backup_test.go
Labels: lgtm, approved, size/S, dco-signoff: yes

#81 tests: Cleanup - move common code
  hack/build/build-functest.sh
  tests/dv_backup_test.go
  tests/framework/backup.go
  tests/framework/storage.go
  tests/framework/vm.go
  tests/resource_filtering_test.go
  tests/utils.go
  tests/vm_backup_test.go
Labels: lgtm, approved, size/XXL, dco-signoff: yes

#95 Update test for paused VM
  tests/resource_filtering_test.go
Labels: lgtm, size/M, approved, dco-signoff: yes

#98 Add new approver
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, dco-signoff: yes

#99 Improve test logs
  hack/config.sh
  tests/framework/backup.go
  tests/framework/framework.go
  tests/framework/storage.go
  tests/framework/vm.go
  tests/resource_filtering_test.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#100 Release doc
  hack/build/releases.md
Labels: lgtm, size/M, approved, dco-signoff: yes

#97 Update kubevirt-ci - running hack/update-kubevirtci.sh
  cluster-up/cluster/k8s-1.24-psa/provider.sh
  cluster-up/cluster/k8s-1.25/provider.sh
  cluster-up/cluster/kind-1.22-sriov/OWNERS
  cluster-up/cluster/kind-1.22-sriov/README.md
  cluster-up/cluster/kind-1.22-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/kind-1.22-sriov/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-1.22-sriov/certcreator/certsecret.go
  cluster-up/cluster/kind-1.22-sriov/certcreator/go.mod
  cluster-up/cluster/kind-1.22-sriov/certcreator/go.sum
  cluster-up/cluster/kind-1.22-sriov/config_sriov_cluster.sh
  cluster-up/cluster/kind-1.22-sriov/conformance.json
  cluster-up/cluster/kind-1.22-sriov/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-1.22-sriov/provider.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/patch-args.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.22-sriov/sriov_operator.sh
  cluster-up/cluster/kind-1.22-sriov/sriovdp_setup.sh
  cluster-up/cluster/kind-1.23-vgpu/README.md
  cluster-up/cluster/kind-1.23-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.23-vgpu/conformance.json
  cluster-up/cluster/kind-1.23-vgpu/provider.sh
  cluster-up/cluster/kind-1.23-vgpu/vgpu-node/node.sh
  cluster-up/cluster/kind-1.23/README.md
  cluster-up/cluster/kind-1.23/provider.sh
  cluster-up/hack/common.sh
  hack/cluster-deploy-prerequisites.sh
  velero-v1.8.1-linux-amd64/LICENSE
  velero-v1.8.1-linux-amd64/examples/README.md
  velero-v1.8.1-linux-amd64/examples/minio/00-minio-deployment.yaml
  velero-v1.8.1-linux-amd64/examples/nginx-app/README.md
  velero-v1.8.1-linux-amd64/examples/nginx-app/base.yaml
  velero-v1.8.1-linux-amd64/examples/nginx-app/with-pv.yaml
Labels: lgtm, approved, size/XXL, dco-signoff: yes
