Repository kubevirt/kubevirt-velero-plugin, pull requests merged in 2023-02, with the labels that each got.

#133 bugfix: should consider excludeded resources by its full name
  pkg/util/util.go
  pkg/util/util_test.go
Labels: ok-to-test, lgtm, size/M, approved, dco-signoff: yes

#128 Test framework for evaluating if a backup integration works properly
  README.md
  hack/build/run-functional-tests.sh
  hack/cluster-deploy-prerequisites.sh
  hack/config.sh
  pkg/util/util.go
  tests/dv_backup_test.go
  tests/framework/framework.go
  tests/framework/kubectl.go
  tests/framework/manifests_utils.go
  tests/framework/storage.go
  tests/framework/vm.go
  tests/manifests/README.md
  tests/manifests/accessCredentialsSecret.yaml
  tests/manifests/blank_datavolume.yaml
  tests/manifests/configmap.yaml
  tests/manifests/dv-for-pvc.yaml
  tests/manifests/dv-with-guest-agent-image.yaml
  tests/manifests/instancetype.yaml
  tests/manifests/preference.yaml
  tests/manifests/secret.yaml
  tests/manifests/vm_for_hotplug.yaml
  tests/manifests/vm_with_access_credentials.yaml
  tests/manifests/vm_with_different_volume_types.yaml
  tests/manifests/vm_with_dv_and_dvtemplate.yaml
  tests/manifests/vm_with_instancetype_and_preference.yaml
  tests/manifests/vm_with_pvc.yaml
  tests/manifests/vmi_with_dv.yaml
  tests/resource_filtering_test.go
  tests/tests_suite_test.go
  tests/utils.go
  tests/vm_backup_test.go
Labels: lgtm, approved, size/XXL, dco-signoff: yes

#136 Fix bug of not initializing global vm
  tests/vm_backup_test.go
Labels: lgtm, approved, size/XS, dco-signoff: yes

#135 add test id
  tests/dv_backup_test.go
  tests/resource_filtering_test.go
Labels: ok-to-test, lgtm, approved, size/XS, dco-signoff: yes

#139 Adjust plugin and tests to run with Data volume GC
  hack/cluster-deploy-prerequisites.sh
  pkg/plugin/dv_backup_item_action.go
  pkg/plugin/vm_backup_item_action_test.go
  pkg/plugin/vmi_backup_item_action_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/dv_backup_test.go
  tests/framework/matcher/helper.go
  tests/framework/matcher/phase.go
  tests/framework/storage.go
  tests/framework/vm.go
  tests/resource_filtering_test.go
  tests/vm_backup_test.go
Labels: lgtm, approved, size/XXL, dco-signoff: yes
