Repository kubevirt/kubevirt-velero-plugin, pull requests merged in 2024-07, with the labels that each got.

#262 Skip restoring hotplug pod
  pkg/plugin/pod_restore_item_action.go
  pkg/plugin/pod_restore_item_action_test.go
Labels: lgtm, approved, size/S, dco-signoff: yes

#261 Support VirtualMachineClusterInstancetype and VirtualMachineClusterPreference
  cmd/velero-backup-restore/velero-backup-restore.sh
  pkg/plugin/vm_backup_item_action.go
  tests/framework/kubectl.go
  tests/framework/manifests_utils.go
  tests/manifests/cluster-instancetype.yaml
  tests/manifests/cluster-preference.yaml
  tests/manifests/vm_with_clusterinstancetype_and_clusterpreference.yaml
  tests/vm_backup_test.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#263 tests: Fix poll of backup phase
  tests/framework/backup.go
Labels: lgtm, approved, size/XS, dco-signoff: yes
