Repository kubevirt/kubevirt-velero-plugin, pull requests merged in 2025-01, with the labels that each got.

#315 [release-v0.7] Ignore VMIs from backup when owner VMs are excluded
  pkg/plugin/vmi_backup_item_action.go
  pkg/plugin/vmi_backup_item_action_test.go
  tests/resource_filtering_test.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#318 fix: update permissions for build-all
  Makefile
Labels: lgtm, approved, size/S, dco-signoff: yes

#323 [release-v0.7] Generate new firmware UUID during restore
  pkg/plugin/vm_restore_item_action.go
  pkg/plugin/vm_restore_item_action_test.go
  pkg/plugin/vmi_restore_item_action.go
  pkg/util/util.go
  tests/vm_backup_test.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#321 VM Object graph: Include backend PVC
  hack/cluster-deploy-prerequisites.sh
  hack/config.sh
  pkg/plugin/vm_restore_item_action.go
  pkg/plugin/vmi_restore_item_action.go
  pkg/util/kvgraph/backup_graph.go
  pkg/util/kvgraph/backup_graph_test.go
  pkg/util/kvgraph/restore_graph.go
  pkg/util/kvgraph/restore_graph_test.go
  pkg/util/kvgraph/util.go
  pkg/util/util.go
  tests/vm_backup_test.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#324 [release-v0.7] VM object graph
  hack/cluster-deploy-prerequisites.sh
  hack/config.sh
  pkg/plugin/dv_backup_item_action.go
  pkg/plugin/vm_backup_item_action.go
  pkg/plugin/vm_backup_item_action_test.go
  pkg/plugin/vm_restore_item_action.go
  pkg/plugin/vmi_backup_item_action.go
  pkg/plugin/vmi_backup_item_action_test.go
  pkg/plugin/vmi_restore_item_action.go
  pkg/util/kvgraph/backup_graph.go
  pkg/util/kvgraph/backup_graph_test.go
  pkg/util/kvgraph/restore_graph.go
  pkg/util/kvgraph/restore_graph_test.go
  pkg/util/kvgraph/util.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/vm_backup_test.go
Labels: lgtm, approved, size/XXL, dco-signoff: yes
